[package]
name = "ushio-geom"
version = "0.1.0"
authors = ["yjHiiragi <tuyijie20180708@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]